# Lower back pain symptoms dataset

In [35]:
import pandas as pd
import numpy as np

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [37]:
df=pd.read_csv("Dataset_spine.csv")
df

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,Class_att,Unnamed: 13
0,63.027817,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal,NaN
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal,NaN
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal,Prediction is done by using binary classificat...
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal,NaN
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,47.903565,13.616688,36.000000,34.286877,117.449062,-4.245395,0.129744,7.8433,14.7484,8.51707,-15.728927,11.5472,Normal,NaN
306,53.936748,20.721496,29.220534,33.215251,114.365845,-0.421010,0.047913,19.1986,18.1972,7.08745,6.013843,43.8693,Normal,NaN
307,61.446597,22.694968,46.170347,38.751628,125.670725,-2.707880,0.081070,16.2059,13.5565,8.89572,3.564463,18.4151,Normal,NaN
308,45.252792,8.693157,41.583126,36.559635,118.545842,0.214750,0.159251,14.7334,16.0928,9.75922,5.767308,33.7192,Normal,NaN
309,33.841641,5.073991,36.641233,28.767649,123.945244,-0.199249,0.674504,19.3825,17.6963,13.72929,1.783007,40.6049,Normal,NaN

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Col1         310 non-null    float64
 1   Col2         310 non-null    float64
 2   Col3         310 non-null    float64
 3   Col4         310 non-null    float64
 4   Col5         310 non-null    float64
 5   Col6         310 non-null    float64
 6   Col7         310 non-null    float64
 7   Col8         310 non-null    float64
 8   Col9         310 non-null    float64
 9   Col10        310 non-null    float64
 10  Col11        310 non-null    float64
 11  Col12        310 non-null    float64
 12  Class_att    310 non-null    object
 13  Unnamed: 13  14 non-null     object
dtypes: float64(12), object(2)
memory usage: 34.0+ KB

In [39]:
df.describe()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,60.496653,17.542822,51.930930,42.953831,117.920655,26.296694,0.472979,21.321526,13.064511,11.933317,-14.053139,25.645981
std,17.236520,10.008330,18.554064,13.423102,13.317377,37.559027,0.285787,8.639423,3.399713,2.893265,12.225582,10.450558
min,26.147921,-6.554948,14.000000,13.366931,70.082575,-11.058179,0.003220,7.027000,7.037800,7.030600,-35.287375,7.007900
25%,46.430294,10.667069,37.000000,33.347122,110.709196,1.603727,0.224367,13.054400,10.417800,9.541140,-24.289522,17.189075
50%,58.691038,16.357689,49.562398,42.404912,118.268178,11.767934,0.475989,21.907150,12.938450,11.953835,-14.622856,24.931950
75%,72.877696,22.120395,63.000000,52.695888,125.467674,41.287352,0.704846,28.954075,15.889525,14.371810,-3.497094,33.979600
max,129.834041,49.431864,125.742385,121.429566,163.071041,418.543082,0.998827,36.743900,19.324000,16.821080,6.972071,44.341200

In [40]:
print("Number of Null value:",df.isnull().sum())

Number of Null value: Col1             0
Col2             0
Col3             0
Col4             0
Col5             0
Col6             0
Col7             0
Col8             0
Col9             0
Col10            0
Col11            0
Col12            0
Class_att        0
Unnamed: 13    296
dtype: int64

In [41]:
print(df.nunique())

Col1           310
Col2           310
Col3           280
Col4           281
Col5           310
Col6           310
Col7           310
Col8           310
Col9           310
Col10          310
Col11          310
Col12          310
Class_att        2
Unnamed: 13     14
dtype: int64

In [42]:
df.columns=['Pelvic_incidence','Pelvic tilt','Lumbar_lordosis_angle','Sacral_slope','Pelvic_radius','Degree_spondylolisthesis','Pelvic_slope','Direct_tilt','Thoracic_slope','Cervical_tilt','Sacrum_angle','Scoliosis_slope','Class_att','Unnamed: 13']

In [43]:
df=df.drop(['Unnamed: 13'],axis=1)
df

,Pelvic_incidence,Pelvic tilt,Lumbar_lordosis_angle,Sacral_slope,Pelvic_radius,Degree_spondylolisthesis,Pelvic_slope,Direct_tilt,Thoracic_slope,Cervical_tilt,Sacrum_angle,Scoliosis_slope,Class_att
0,63.027817,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,47.903565,13.616688,36.000000,34.286877,117.449062,-4.245395,0.129744,7.8433,14.7484,8.51707,-15.728927,11.5472,Normal
306,53.936748,20.721496,29.220534,33.215251,114.365845,-0.421010,0.047913,19.1986,18.1972,7.08745,6.013843,43.8693,Normal
307,61.446597,22.694968,46.170347,38.751628,125.670725,-2.707880,0.081070,16.2059,13.5565,8.89572,3.564463,18.4151,Normal
308,45.252792,8.693157,41.583126,36.559635,118.545842,0.214750,0.159251,14.7334,16.0928,9.75922,5.767308,33.7192,Normal
309,33.841641,5.073991,36.641233,28.767649,123.945244,-0.199249,0.674504,19.3825,17.6963,13.72929,1.783007,40.6049,Normal

In [44]:
df["Class_att"].unique()
df["Class_att"]=df["Class_att"].replace({'Abnormal':1, 'Normal':2})
print(df)

     Pelvic_incidence  Pelvic tilt  Lumbar_lordosis_angle  Sacral_slope  \
0           63.027817    22.552586              39.609117     40.475232
1           39.056951    10.060991              25.015378     28.995960
2           68.832021    22.218482              50.092194     46.613539
3           69.297008    24.652878              44.311238     44.644130
4           49.712859     9.652075              28.317406     40.060784
..                ...          ...                    ...           ...
305         47.903565    13.616688              36.000000     34.286877
306         53.936748    20.721496              29.220534     33.215251
307         61.446597    22.694968              46.170347     38.751628
308         45.252792     8.693157              41.583126     36.559635
309         33.841641     5.073991              36.641233     28.767649

     Pelvic_radius  Degree_spondylolisthesis  Pelvic_slope  Direct_tilt  \
0        98.672917                 -0.254400      0.744503      12.5661
1       114.405425                  4.564259      0.415186      12.8874
2       105.985135                 -3.530317      0.474889      26.8343
3       101.868495                 11.211523      0.369345      23.5603
4       108.168725                  7.918501      0.543360      35.4940
..             ...                       ...           ...          ...
305     117.449062                 -4.245395      0.129744       7.8433
306     114.365845                 -0.421010      0.047913      19.1986
307     125.670725                 -2.707880      0.081070      16.2059
308     118.545842                  0.214750      0.159251      14.7334
309     123.945244                 -0.199249      0.674504      19.3825

     Thoracic_slope  Cervical_tilt  Sacrum_angle  Scoliosis_slope  Class_att
0           14.5386       15.30468    -28.658501          43.5123          1
1           17.5323       16.78486    -25.530607          16.1102          1
2           17.4861       16.65897    -29.031888          19.2221          1
3           12.7074       11.42447    -30.470246          18.8329          1
4           15.9546        8.87237    -16.378376          24.9171          1
..              ...            ...           ...              ...        ...
305         14.7484        8.51707    -15.728927          11.5472          2
306         18.1972        7.08745      6.013843          43.8693          2
307         13.5565        8.89572      3.564463          18.4151          2
308         16.0928        9.75922      5.767308          33.7192          2
309         17.6963       13.72929      1.783007          40.6049          2

[310 rows x 13 columns]

In [45]:
df["Class_att"].value_counts()

1    210
2    100
Name: Class_att, dtype: int64

In [46]:
#y=df["Class_att"]
#X=df.drop(["Class_att"],axis=1)
#X

In [47]:
def preprocessing (df):
    df=df.copy()

In [48]:
#splitting
y=df["Class_att"].copy()
X=df.drop("Class_att",axis=1).copy()
X

,Pelvic_incidence,Pelvic tilt,Lumbar_lordosis_angle,Sacral_slope,Pelvic_radius,Degree_spondylolisthesis,Pelvic_slope,Direct_tilt,Thoracic_slope,Cervical_tilt,Sacrum_angle,Scoliosis_slope
0,63.027817,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171
...,...,...,...,...,...,...,...,...,...,...,...,...
305,47.903565,13.616688,36.000000,34.286877,117.449062,-4.245395,0.129744,7.8433,14.7484,8.51707,-15.728927,11.5472
306,53.936748,20.721496,29.220534,33.215251,114.365845,-0.421010,0.047913,19.1986,18.1972,7.08745,6.013843,43.8693
307,61.446597,22.694968,46.170347,38.751628,125.670725,-2.707880,0.081070,16.2059,13.5565,8.89572,3.564463,18.4151
308,45.252792,8.693157,41.583126,36.559635,118.545842,0.214750,0.159251,14.7334,16.0928,9.75922,5.767308,33.7192
309,33.841641,5.073991,36.641233,28.767649,123.945244,-0.199249,0.674504,19.3825,17.6963,13.72929,1.783007,40.6049

In [49]:
#scaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)

In [50]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,shuffle=True,random_state=123)

In [51]:
X_train

,Pelvic_incidence,Pelvic tilt,Lumbar_lordosis_angle,Sacral_slope,Pelvic_radius,Degree_spondylolisthesis,Pelvic_slope,Direct_tilt,Thoracic_slope,Cervical_tilt,Sacrum_angle,Scoliosis_slope
148,0.305603,-0.771599,-0.059816,0.967730,-1.017285,0.346962,-1.373680,1.658189,-1.654637,0.068533,0.728301,1.688657
82,1.634479,1.155567,-0.235729,1.237228,0.289121,0.680275,1.043141,-0.942015,0.175147,1.155691,0.806514,0.698508
287,-1.595412,-1.788149,-1.773896,-0.715406,0.185618,-0.451815,-1.071305,-0.478295,-0.535590,-0.965413,-1.233951,1.464383
268,-0.194716,-0.105456,-0.490646,-0.171405,-0.309455,-0.567531,-0.874193,0.513244,-1.047459,-1.686068,-1.459046,-0.124000
7,-0.879201,-0.679253,-1.235826,-0.622522,-0.048932,-0.985977,-1.195150,0.868934,-1.560566,-1.496820,-0.905985,0.067888
...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.262491,-0.771059,0.313370,0.911968,-1.743557,0.624034,-1.124981,-0.802614,-1.226233,-0.377473,1.689925,0.906345
83,1.197502,0.725702,1.401206,0.996617,2.551106,1.037856,1.748973,-1.246311,-0.539331,0.471421,0.156804,-1.322378
17,-1.698016,-1.440943,-1.045553,-1.106037,0.834150,-0.604657,0.215550,1.141105,1.633477,-1.209279,1.518581,-0.095334
230,0.297242,0.559948,0.574994,-0.035813,0.466862,-0.810168,1.837440,1.011037,1.342777,0.504551,-0.189813,-0.402205
98,0.997081,0.489396,2.265255,0.915450,0.386214,0.931093,1.583888,-0.738664,0.584755,-1.508033,1.176571,0.773851

In [52]:
y_train

148    1
82     1
287    2
268    2
7      1
      ..
106    1
83     1
17     1
230    2
98     1
Name: Class_att, Length: 217, dtype: int64

In [53]:
model_1=LogisticRegression()
model_1.fit(X_train,y_train)
model_1.score(X_test,y_test)
model_1.score(X_test,y_test)*100

84.94623655913979

In [54]:
model_2=DecisionTreeClassifier()
model_2.fit(X_train,y_train)
model_2.score(X_test,y_test)
model_2.score(X_test,y_test)*100

75.26881720430107

In [55]:
model_3=RandomForestClassifier()
model_3.fit(X_train,y_train)
model_3.score(X_test,y_test)
model_3.score(X_test,y_test)*100

78.49462365591397

In [56]:
model_4=GradientBoostingClassifier()
model_4.fit(X_train,y_train)
model_4.score(X_test,y_test)
model_4.score(X_test,y_test)*100

80.64516129032258